### ISSUE TITLE
external(trailpack-ts3client): Project Satus questions 

### ISSUE THREAD

**Issue by maissani** [schroffl/alfred-teamspeak#2]
# trailpack-ts3client
## What is that ?

A future package ( bundle ) using alfred teamspeak for Trails an ES6 Framework. 
It will provide Alfred-teamspeak as a service with some complementary function that simply some actions like sendtoAll or getTeamspeakSession(list of user that contains ip, connectiontime, country etc...)...
## Where it will be published ?

There: https://github.com/FriendsOfTrails/trailpack-ts3client
## Why we use Alfred-Teamspeak

Well written librairy, we hope that it's actively maintained.
## What we need from alfred-teamspeak

Stay actively maintened
## The question:

Can you confirm that if there is any change in teamspeak specs, this package will stay maintained ?

**Comment by schroffl** [comment]
Hey,

I am not actively keeping up-to-date with the specification and I haven't finished writing all the docs yet.
But if you'd just open an issue for any updates, I would take care of it as fast as I can ;)

**Comment by maissani** [comment]
:) , This is not a problem, your réactivity means that the project is actively maintained. 
We will lock the use of alfred-teamspeak in trailpack-ts3client.

Thx a lot for this answer. 

You can close this issue at any-time

Best Regards, 
Cordialy
Mehdi AISSANI
