### ISSUE TITLE
Need Examples when functions was having callbacks

### ISSUE THREAD

**Issue by maissani** [schroffl/alfred-teamspeak#3]
Hi, 
The afred teamspeak api change, and i am hardly trying to reproduce the same behavior on our app. 
Can you provide use some examples 

```
const bot = new Alfred({
    'name': 'mybotname',
    'host': 'hosturl',
  });
  var clientsInfos = new Array();
  var botLogin = bot.login('username','password');
 // I try to use promise but i fail because i do not know how it works 
  getConnected = function() {
    return new Promise((resolve, reject) => {
      botLogin.then(() => bot.send('clientlist'))
      .then(res => console.log(data))
      .then(resolve).catch(reject);
    });
  }
  getConnected();

 // Not working on v4 need some help to reproduce with the v4 usages
  bot.login('username','password').then(() => {
    console.log("login")
    bot.send("clientlist", function(err, response, rawResponse){
      console.log("login2")
      for (var tsclient in response) {console.log("login3")
        bot.send("sendtextmessage", {targetmode:1, target:response[tsclient]['clid'], msg:"Your ip has been stored into our database for statistics"})
        bot.send("clientinfo",{clid: response[tsclient]['clid']}, function(err, response, rawResponse){
          //console.log(response);
          clientsInfos[response['cid']] = {
            id: response['client_unique_identifier'],
            nickname: response['client_nickname'],
            servergroups: response['client_servergroups'],
            country: response['client_country'],
            ip: response['connection_client_ip']
          }
          console.log(clientsInfos[response['cid']]);
        })
      }
    });
    console.log(clientsInfos);
  }).catch(err => {
  // Encountered an error during the login process
  console.error(err);
  });*/

```

**Comment by schroffl** [comment]
I am not using node-teamspeak anymore. Instead I'm using [my own library](https://github.com/schroffl/teamspeak-query). So getting all clients would be:

``` javascript
const bot = new Alfred({ ... }); 

bot.login('username', 'password')
  .then(() => bot.send('clientlist'))
  .then(clientlist => {
    // Do your stuff
  })
  .catch(console.error);
```

**Comment by maissani** [comment]
It's better :) 
Your own library is well written, i love the job that you have done on your libraries.

**Comment by maissani** [comment]
I'm trying to use you user API 

When i try to catch user text message get what the bot send to users but i get nothing when i send message from users to bot

I want to implement something like: **when a user type and send to bot !hello the bot respond to user the string world.**
Can you help me ? 

```
  const bot = new Alfred({
    'name': 'botname',
    'host': 'hostname',
  });
    const User = Alfred.User;
    bot.use(User);
    bot.login('username','pasword')
    .then(() => bot.send('clientlist'))
    .then(clientlist => {
      console.log(clientlist);
      for(clients in clientlist.clid) {
        console.log('Send Message to client : '+ clientlist.clid[clients])
        bot.send('sendtextmessage',{'targetmode':1, 'target': clientlist.clid[clients], 'msg':"Hello World all"})
      }
    })
    .catch(console.error);

    bot.on('textmessage', data => {
      console.log('Recieved message from client: '+ data.msg)
      data.user.poke(data.msg)
    })

```

Thx
Best Regards

**Comment by schroffl** [comment]
``` javascript
const bot = new Alfred({ 'host': 'hostname' });

bot.use(Alfred.User);

bot.login('username', 'password')
  .then(() => bot.send('servernotifyregister', { 'event': 'textprivate' }))
  .catch(console.error)

bot.on('textmessage', data => {
  if(data.msg === '!hello') data.user.respond('world');
});

```

**Comment by maissani** [comment]
Is it normal that when i pass mail from user to bot like !register email@example.com password, i get data.msg = !register[URL  (result obtained by a simple console.log(data.msg)
This sounds like that teamspeak transform emails as [URL=mailto: email@example.com ] email@example.com [/URL]
With the side effect that teamspeak-query from your package doesn't escape users messages things.
Can you fix that or provide a parrameter on text message to escape things ?

**Comment by schroffl** [comment]
Yes, sounds like it but it's not specified in the TeamspeakQuery Documentation so I'm not going to implement it. You have to try and parse it yourself I'm afraid.

**Comment by maissani** [comment]
If i send !register contact@mehdiaissani.com password 
console.log(util.inspect(data.msg)); sends back '!register[URL' 
You have to escape strings in your teamspeak query package please.

**Comment by maissani** [comment]
I'm pretty sure that if i want to inject code it will works.... please escape it!!!

**Comment by maissani** [comment]
Even if user send  !register[URL=mailto: email@example.com ] email@example.com [/URL] you have to catch all the message and escape it to obtain data.msg = "!register[URL=mailto: email@example.com ] email@example.com [/URL]" and not "!register[URL="
Because you don't escape the strings the output is not always the same as user have write.

**Comment by maissani** [comment]
Can i make a PR if you just dont want to do that. 
This is not because it's not spécified, that because your library not fit perfect for the moment. You don't cover the fact that textprivate or text imply that you have to escape it or convert it to string.

**Comment by schroffl** [comment]
I think I got what you mean, I'm going to take a look at it.

**Comment by schroffl** [comment]
The bug in [teamspeak-query](https://github.com/schroffl/teamspeak-query) is fixed as of version `1.5.3`.

**Comment by maissani** [comment]
:) Befor you do all the work 

in parse(str):

Instead of index of i have made that : 

```
                v = v.split(/^([^=]+)=/);
                v.shift();
                v = v.map(TeamspeakQuery.unescape);

```

**Comment by maissani** [comment]
This works weel , thx a lot for réactivity. 
Now i can continue to building a package that use alfred-teamspeak with the guarantee that it's the best package for interact with a teamspeak server.

Thx a lot, 
If i can send you a beer or money i ll tip for you. 

Best Regards.
