### ISSUE TITLE
feat/request(timeout): Bot Disconnect Timeout after 1 minute

### ISSUE THREAD

**Issue by maissani** [schroffl/alfred-teamspeak#4]
# Feature / Request : The TimeOut Parameter
## Intro

In most of case when not using bot commands for 1 minute the bot disconnect. 
This cause loose bot from view for the client and in most of case the bot cannot catch new events.
## What's need to be done : Add a Timeout parameter to Alfred Teamspeak
- [x] Alfred need a timeout parameter
- [x] When set to 0 it will never disconnect
- [x] Must be set in milliseconds.
## Outro

It will help when notify text message or when catching any event from server.

Best Regards, 
 :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1:  :+1: 
Have a nice day and thanks for this powerfull node package.
Mehdi Aissani

**Comment by schroffl** [comment]
You can access the instance of `teamspeak-query` via `Alfred.query` so you can just use the native [net.Socket.setTimeout](https://nodejs.org/api/net.html#net_socket_settimeout_timeout_callback) (or basically do whatever you want with the socket) like this:

``` javascript
Alfred.query.sock.setTimeout(...);
```

**Comment by maissani** [comment]
Thanks a lot

**Comment by maissani** [comment]
# Bug

Alfred.query is not defined. 
I think it's because in Alfred lib there is no this.query in constructor.
Can you take a view about that or provide a working example ? 
This is the same when try to interact with throttle

Alfred.query => Undefined

**Comment by schroffl** [comment]
Yes, sorry it's being initiated in `Alfred.login`. Gonna fix it right now.
