### ISSUE TITLE
help/wanted(throttle): How to setup Teamspeak QUery throttle in Alfred

### ISSUE THREAD

**Issue by maissani** [schroffl/alfred-teamspeak#5]
# How to Setup the throttle using Alfred.
## Question

Hi, 
I need to know how to set up the throttle that is used by teamspeak query from Alfred. 
Can you give me an hint about how to setup that ? 

Best Regards, 
Mehdi AISSANI

**Comment by schroffl** [comment]
You can access the instance of `teamspeak-query` via `Alfred.query`.
Using the throttle:

``` javascript
Alfred.query.throttle // Do whatever you want
```

**Comment by maissani** [comment]
I'm realy sorry of this issue spamming :(
I ask question that not under documentation.
But it will improve the future users of this Beautifull package.

Best Regards.

**Comment by schroffl** [comment]
That's what this feature is there for :)

**Comment by maissani** [comment]
Can you fix Alfred Query issue. 
And five an example about how to use it :

``` JavaScript
Alfred.query.throttle = {'enable': false }; //????
Alfred.query.throttle( 'enable', false );
```

Thx a lot.

**Comment by schroffl** [comment]
`Alfred.query.throttle.set('enable', false);` It's specified in the documentation of `teamspeak-query`

**Comment by maissani** [comment]
Thx a lot <3 , if i can buy you a beer or anything to tip your project i am open. 

Best Regards, 
Mehdi AISSANI
